require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OccupantsController do

  def mock_occupant(stubs={})
    @mock_occupant ||= mock_model(Occupant, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all occupants as @occupants" do
      Occupant.stub(:all) { [mock_occupant] }
      get :index
      assigns(:occupants).should eq([mock_occupant])
    end
  end

  describe "GET show" do
    it "assigns the requested occupant as @occupant" do
      Occupant.stub(:find).with("37") { mock_occupant }
      get :show, :id => "37"
      assigns(:occupant).should be(mock_occupant)
    end
  end

  describe "GET new" do
    it "assigns a new occupant as @occupant" do
      Occupant.stub(:new) { mock_occupant }
      get :new
      assigns(:occupant).should be(mock_occupant)
    end
  end

  describe "GET edit" do
    it "assigns the requested occupant as @occupant" do
      Occupant.stub(:find).with("37") { mock_occupant }
      get :edit, :id => "37"
      assigns(:occupant).should be(mock_occupant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created occupant as @occupant" do
        Occupant.stub(:new).with({'these' => 'params'}) { mock_occupant(:save => true) }
        post :create, :occupant => {'these' => 'params'}
        assigns(:occupant).should be(mock_occupant)
      end

      it "redirects to the created occupant" do
        Occupant.stub(:new) { mock_occupant(:save => true) }
        post :create, :occupant => {}
        response.should redirect_to(occupant_url(mock_occupant))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved occupant as @occupant" do
        Occupant.stub(:new).with({'these' => 'params'}) { mock_occupant(:save => false) }
        post :create, :occupant => {'these' => 'params'}
        assigns(:occupant).should be(mock_occupant)
      end

      it "re-renders the 'new' template" do
        Occupant.stub(:new) { mock_occupant(:save => false) }
        post :create, :occupant => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested occupant" do
        Occupant.stub(:find).with("37") { mock_occupant }
        mock_occupant.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :occupant => {'these' => 'params'}
      end

      it "assigns the requested occupant as @occupant" do
        Occupant.stub(:find) { mock_occupant(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:occupant).should be(mock_occupant)
      end

      it "redirects to the occupant" do
        Occupant.stub(:find) { mock_occupant(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(occupant_url(mock_occupant))
      end
    end

    describe "with invalid params" do
      it "assigns the occupant as @occupant" do
        Occupant.stub(:find) { mock_occupant(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:occupant).should be(mock_occupant)
      end

      it "re-renders the 'edit' template" do
        Occupant.stub(:find) { mock_occupant(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested occupant" do
      Occupant.stub(:find).with("37") { mock_occupant }
      mock_occupant.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the occupants list" do
      Occupant.stub(:find) { mock_occupant }
      delete :destroy, :id => "1"
      response.should redirect_to(occupants_url)
    end
  end

end
